/* 
____________________________________________________________________________________
Exploratory Data Analysis
Author:         Tatiana Rodriguez
Last updated:   2026-19-05

This script contains examples of data exploration queries. 
Views and tables from datawarehouse_TMR are used, make sure to download and run the
requiered scripts and source data files.
____________________________________________________________________________________
*/

-- =================================================================================
-- DIMENSION EXPLORATION
-- =================================================================================

-- Explore all tables in the db
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore all columns in the db
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers' -- for example.

-- Dimensions exploration: identify unique values/categories in each dimension.
-- This helps us understand how data might be greouped or segmented for analysis
SELECT DISTINCT category, subcategory, product_name FROM gold.dim_products
ORDER BY 1, 2, 3


-- =================================================================================
-- DATE EXPLORATION
-- =================================================================================


SELECT MIN(order_date) first_order_date, MAX(order_date) last_order_date,
DATEDIFF(year,MIN(order_date),MAX(order_date)) AS order_range_years,
DATEDIFF(month,MIN(order_date),MAX(order_date)) AS order_range_month
FROM gold.fact_sales


SELECT 
DATEDIFF(year, MAX(birth_date),GETDATE()) AS youngest_customer,
DATEDIFF(year, MIN(birth_date),GETDATE()) AS oldest_customer
FROM gold.dim_customers


/*=================================================================================
MEASURES EXPLORATION

Calculate the key metric of the business ("big numbers")
This step entails the highest level of aggregation and the lowest level of details.
=================================================================================*/

-- Total sales
SELECT SUM(sales) AS total_sales FROM gold.fact_sales

-- How many items have been sold
SELECT SUM(quantity) AS total_items_sold FROM gold.fact_sales

-- Average selling price
SELECT AVG(price) AS average_price FROM gold.fact_sales

-- Total number of orders
SELECT COUNT(order_number) AS total_orders FROM gold.fact_sales
SELECT COUNT(DISTINCT(order_number)) AS total_orders FROM gold.fact_sales

-- Total number of products sold
SELECT COUNT(product_key) AS products_sold FROM gold.dim_products

-- Total number of customers
SELECT COUNT(customer_key) AS customers FROM gold.dim_customers

-- Total number of customers that have placed an order
SELECT COUNT(customer_key) AS ordering_customers FROM gold.fact_sales

-- ________________________________________________________________________________

-- Report of all key business metrics:

-- Total sales revenue
SELECT 'Total Sales' AS measure_name, SUM(sales) AS measure_value FROM gold.fact_sales
-- Total sales quantity
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
-- Average selling price
UNION ALL
SELECT 'Average Price' AS measure_name, AVG(price) AS measure_value FROM gold.fact_sales
-- Total number of orders
UNION ALL
SELECT 'Total Nr. Orders' AS measure_name, COUNT(order_number) AS measure_value FROM gold.fact_sales
-- Total number of products sold
UNION ALL
SELECT 'Total Nr. Products' AS measure_name, COUNT(product_key) AS measure_value FROM gold.dim_products
-- Total number of customers
UNION ALL
SELECT 'Total Nr. Customers' AS measure_name, COUNT(customer_key) AS measure_value FROM gold.dim_customers

/*=================================================================================
MAGNITUDE ANALYSIS

Compare the measure values by categories to understand their importance.
The equation is [measure] by [dimension]
=================================================================================*/

-- Total customers by country
SELECT 
    country, 
    COUNT(customer_key) AS total_customers 
FROM gold.dim_customers
GROUP BY country 
ORDER BY total_customers DESC

-- Total customers by gender
SELECT 
    gender, 
    COUNT(customer_key) AS total_customers 
FROM gold.dim_customers
GROUP BY gender 
ORDER BY total_customers DESC

-- Total products sold by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- Average cost per category
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

-- Total revenue generated by category
SELECT
    p.category,
    SUM(f.sales) total_revenue
FROM gold.fact_sales f 
LEFT JOIN gold.dim_products p  
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- Revenue generated by customer
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales) AS total_revenue
FROM gold.fact_sales f  
LEFT JOIN gold.dim_customers c  
    ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name 
ORDER BY total_revenue DESC

-- Distribution of sales per country
SELECT
    c.country,
    SUM(f.quantity) AS total_sales_quantity
FROM gold.fact_sales f  
LEFT JOIN gold.dim_customers c  
    ON c.customer_key = f.customer_key
GROUP BY c.country 
ORDER BY total_sales_quantity DESC


/*=================================================================================
RANKING ANALYSIS

Order the values of dimensions by measure to identify top and bottom performers
Equation is rank[dimension] by [measure]
=================================================================================*/

-- Which 5 products generate the highest revenue?
SELECT TOP 5
    p.product_name,
    SUM(f.sales) total_revenue
FROM gold.fact_sales f 
LEFT JOIN gold.dim_products p  
    ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC

-- -- Alternatively, if you need more flexibility, a window function can be used.
-- SELECT * FROM (
--     SELECT 
--         p.product_name,
--         SUM(f.sales) total_revenue,
--     ROW_NUMBER() OVER (ORDER BY SUM(f.sales) DESC) AS rank_products
--     FROM gold.fact_sales f 
--     LEFT JOIN gold.dim_products p  
--         ON p.product_key = f.product_key
--     GROUP BY p.product_name
-- )t
-- WHERE rank_products <= 5

-- Which 5 products generate the least revenue?
SELECT TOP 5
    p.product_name,
    SUM(f.sales) total_revenue
FROM gold.fact_sales f 
LEFT JOIN gold.dim_products p  
    ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC

-- Top 3 customers
SELECT TOP 3
    c.customer_key,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales f  
LEFT JOIN gold.dim_customers c  
    ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_orders
